### PR TITLE
Better UI for macOS

### PR DESCRIPTION
**Pull request by FormalSnake**
Screenshot 2023-06-29 at 11 56 34

The UI is cleaner, untested on windows 10/11. If someone can help me I can automatically change blur and mica depending on windows 10/11.

### CODE REVIEW

**Comment by FormalSnake** [comment]
sorry if the code changed slightly, it is because I use prettier to format code.

**Comment by FormalSnake** [comment]
The reason for this PR is to be more in-par with the macOS file explorer

**Comment by FormalSnake** [comment]
Thanks!

**Comment by conaticus** [comment]
Looks quite different on Windows, not sure why but will be a platform specific thing:

image
image

**Comment by FormalSnake** [comment]
That is becaue apply_blur is deprecated on win11, so that needs to use mica instead. But mica is not on windows 10, so I need some sort of detection for it.

**Comment by FormalSnake** [comment]
you can find more info in issues: https://github.com/tauri-apps/window-vibrancy/issues?q=windows

**Comment by ProtogenDelta** [comment]
This PR targets the main branch. All prospective changes should target `dev`.

**Pull request closed without merging**
