### PR TITLE
Makes the search functionality more extensible 

### PR DESCRIPTION
**Pull request by RaphGL**
This PR adds a pipeline that rejects files from a search based on filters and refactors to code to be more understandable and extensible.

All input is welcome. 
Note: Due to running rustfmt the commit is polluted. All the relevant work is in `src-tauri/src/search.rs`

### CODE REVIEW

**Comment by conaticus** [comment]
@ProtogenDelta had already started refactoring this so we're going to prioritise his and see if we can take anything useful from yours and add it to his.

Like I said please make issues and check first before making PRs or they're not going to get accepted.

**Comment by RaphGL** [comment]
@conaticus I told u about it in a message a few days ago as well as on call saying I would be working on this then I sent a message about it on the server this morning that got no response so I just started working on it. 

But got it. I'll just pick up on another issue some other time.

**Comment by conaticus** [comment]
@ProtogenDelta Are you continuing on the refactor or can I merge this?

**Comment by ProtogenDelta** [comment]
@conaticus still working, hoping to get some more changes out today, uncertain if I'll be able to though.

**Pull request closed without merging**
